[tool.poetry]
name = "sqs_hbs"
version = "0.1.0"
description = """
Self-Quantification System for Health Behavior Support.
This is an experimental project for my PhD work aiming
at providing users with personalized recommendations to
increase their physical activity level.
"""
authors = ["Ziip <paul.dulaud@utt.fr>"]
license = "AGPL3"

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.0.3"
django-environ = "^0.8.1"
django-simple-bulma = "^2.5.0"
whitenoise = "^6.0.0"

[tool.poetry.dev-dependencies]
doc8 = "^0.10.1"
rstcheck = "^3.3.1"
esbonio = "^0.10.2"
django-fitbit = {path = "../django-fitbit", develop = true}
livereload = "^2.6.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
